# Generated by Django 4.0.3 on 2022-04-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_contactinfo_alter_myskill_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='skillimage/')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, max_length=500)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.TextField(max_length=50)),
                ('UserEmail', models.EmailField(max_length=150)),
                ('UserPassword', models.TextField(max_length=150)),
                ('UserConPassword', models.TextField(max_length=150)),
            ],
        ),
    ]
