# Generated by Django 4.0.3 on 2022-04-30 21:05

from django.db import migrations, models
import skill.models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_blog_userregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddVolunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=50)),
                ('Address', models.TextField(max_length=50)),
                ('BloodGroup', models.TextField(max_length=50)),
                ('Email', models.TextField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=skill.models.filepath)),
            ],
        ),
        migrations.AlterModelTable(
            name='userregister',
            table='skill_userregister',
        ),
    ]
