# Generated by Django 4.0.3 on 2022-05-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0005_alter_addvolunteers_name_alter_myskill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myskill',
            name='email',
            field=models.EmailField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='addvolunteers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skillimage'),
        ),
    ]
