# Generated by Django 4.0.3 on 2022-05-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0006_myskill_email_alter_addvolunteers_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myskill',
            name='email',
        ),
        migrations.AddField(
            model_name='myskill',
            name='descc',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
